### ISSUE TITLE
Not compatible with M2.3.2

### ISSUE THREAD

**Issue by realchriswells** [yireo/magento2-corshack#2]
I had the module installed to 2.3.1 and everything worked, but in 2.3.2 for some reason I am getting the CORS errors again.

Is there an incompatibility with 2.3.2, or am I doing something wrong?

**Comment by jissereitsma** [comment]
I've just checked it under Magento 2.3.2 myself and it seems to be working. Please note that normally we would say that a module is compatible with Magento version X, if it installs and delivers no errors. In this case, it seems that the module is compatible with Magento 2.3.2 (because it installs just fine and delivers no errors). When visit a Magento URL `http://example.org/graphql` (please note the GraphQL suffix), I'm able to inspect the HTTP headers in my browser and can confirm that it still displays two HTTP headers added by this module: The header `Access-Control-Allow-Headers` with value `Content-Type,Authorization` and the header `Access-Control-Allow-Origin` with value `*` (because this is the wildcard I configured in the module options). Could you test a similar thing and let us know the details?

**Comment by ghost** [comment]
Hi Jisse,

I think it's also possible to change the headers in Magento's nginx configuration by adding those two lines in the nginx config.

`add_header Access-Control-Allow-Origin "*";
add_header Access-Control-Allow-Headers "Content-Type, Authorization";`

I commented the line below because I didn't got any CORS errors if the line was commented.
`
#add_header Access-Control-Allow-Credentials "true";
`
If you add those lines to your nginx config the module is no longer necessary.

Kind regards,
Mike Verhaert

**Comment by jissereitsma** [comment]
@miketechtwo Completely true. There is also an Apache equivalent. But this was written for people that don't have the access to those configurations. Just for ease of use.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.
